#!/bin/zsh

# Config
GITHUB_TOKEN="ghp_yourTokenHere"
REPO_OWNER="repasscloud"
REPO_NAME="AvaPlatform-Issues"
NUM_ISSUES=30

# Valid tags
VALID_CAT_TAGS=("cat-auth" "cat-billing" "cat-uiux" "cat-data" "cat-onboarding" "cat-performance" "cat-access")
PRIORITY_TAGS=("p-1" "p-2" "p-3" "p-4" "p-5")

# Sample titles and bodies
TITLES=(
  "Fix login redirect"
  "Improve billing retries"
  "Update onboarding flow"
  "Optimize dashboard queries"
  "Refactor access control"
  "Add UI theme support"
  "Improve data fetch times"
)

BODIES=(
  "This is a randomly generated issue for testing purposes.\n\n### Steps to Reproduce:\n- Do a thing\n- Observe behavior"
  "Please investigate and resolve. Refer to logs if needed.\n\n---\n- Expected outcome: Something useful\n- Actual outcome: Error 500"
  "Refactor code to improve maintainability and testability.\n\n_This task was autogenerated._"
)

# Generate and create issues
for i in {1..$NUM_ISSUES}; do
  TITLE="${TITLES[$RANDOM % ${#TITLES[@]} + 1]}"
  BODY="${BODIES[$RANDOM % ${#BODIES[@]} + 1]}"
  CAT_LABEL="${VALID_CAT_TAGS[$RANDOM % ${#VALID_CAT_TAGS[@]} + 1]}"
  PRIORITY_LABEL="${PRIORITY_TAGS[$RANDOM % ${#PRIORITY_TAGS[@]} + 1]}"

  echo "Creating issue #$i with [$CAT_LABEL, $PRIORITY_LABEL]..."

  curl -s -X POST "https://api.github.com/repos/$REPO_OWNER/$REPO_NAME/issues" \
    -H "Authorization: token $GITHUB_TOKEN" \
    -H "Accept: application/vnd.github+json" \
    -d @- <<EOF
{
  "title": "$TITLE",
  "body": "$BODY",
  "labels": ["$CAT_LABEL", "$PRIORITY_LABEL"]
}
EOF

  sleep 1  # avoid GitHub abuse rate limits
done

echo "✅ Done creating $NUM_ISSUES issues."
