# .github/workflows/docker-compose-pr.yml
name: Docker Compose Build → PR → Auto-merge

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout dev
        uses: actions/checkout@v4
        with:
          ref: dev

      - name: Build with Docker Compose
        run: docker compose build ava-api

  create_pr:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout dev
        uses: actions/checkout@v4
        with:
          ref: dev

      - name: Create or update PR
        id: cpr
        uses: peter-evans/create-pull-request@v7
        with:
          branch-token: ${{ secrets.GITHUB_TOKEN }}    # was `git-token` in v6, now renamed :contentReference[oaicite:0]{index=0}
          title:        'Automated PR: dev → main'
          body:         automerged
          base:         main
          branch:       dev                             # fixed-name PR branch → updates existing PR by default

      - name: Enable auto-merge
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token:                 ${{ secrets.GITHUB_TOKEN }}
          pull-request-number:   ${{ steps.cpr.outputs.pull-request-number }}
          merge-method:          merge                 # merge, squash or rebase :contentReference[oaicite:1]{index=1}
